project_name: iawc
builds:
  - main: .
    binary: iawc
    # refer to the https://pkg.go.dev/cmd/link
    ldflags:
      - -s -w -X main.Revision={{.ShortCommit}}
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - '386'
      - amd64
      - arm64
changelog:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
archives:
  - id: foo
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - iawc.yaml
release:
  prerelease: auto
brews:
  - tap:
      owner: kemokemo
      name: homebrew-tap
    homepage: "https://github.com/kemokemo/iawc"
    description: "This tool check and report inappropriate words in your documents."
    install: |
      bin.install "iawc"
scoop:
  bucket:
    owner: kemokemo
    name: scoop-bucket
  homepage:  https://github.com/kemokemo/iawc
  description: This tool check and report inappropriate words in your documents.
  license: MIT
